{
  "language": "generic",
  "before-install": [
    "sudo apt-get update -qq",
    "sudo apt-get install -qq nodejs"
  ],
  "services": [
    "docker"
  ],
  "env": "JDKVER=jdk8",
  "install": true,
  "before-script": [
    "docker pull mdernst/ubuntu-for-cf-$JDKVER"
  ],
  "script": [
    "REMOTE_ORIGIN_URL=`git config --get remote.origin.url`",
    "echo \"JDKVER=${JDKVER}\"",
    "echo \"TRAVIS_BRANCH=${TRAVIS_BRANCH}\"",
    "echo \"REMOTE_ORIGIN_URL=${REMOTE_ORIGIN_URL}\"",
    "echo \"TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}\"",
    "echo \"TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}\"",
    "echo \"TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}\"",
    "echo \"TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}\"",
    "docker run mdernst/ubuntu-for-cf-$JDKVER /bin/bash -c \"true &&\n   export JAVA_HOME=\\`which javac|xargs readlink -f|xargs dirname|xargs dirname\\` &&\n   if [ $TRAVIS_EVENT_TYPE = pull_request ] ; then\n     git clone --quiet --depth 9 $REMOTE_ORIGIN_URL $TRAVIS_BUILD_DIR/checker-framework-inference\n     cd $TRAVIS_BUILD_DIR/checker-framework-inference\n     git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge\n     git checkout -qf FETCH_HEAD\n     git config user.email noone@cares.com\n     git config user.name Noone Cares\n     git remote add theupstream https://github.com/$TRAVIS_REPO_SLUG.git\n     git pull --depth 9 theupstream $TRAVIS_BRANCH\n   else\n     git clone --quiet -b $TRAVIS_BRANCH --depth 9 $REMOTE_ORIGIN_URL $TRAVIS_BUILD_DIR/checker-framework-inference\n     cd $TRAVIS_BUILD_DIR/checker-framework-inference checker-framework-inference\n   fi &&\n   java -version &&\n   javac -version &&\n   export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 &&\n   export TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG &&\n   export TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR &&\n   ./.travis-build.sh\""
  ],
  "sudo": false,
  "after-script": [
    "set +e\ndeclare exitCode;\ncurl -sSL https://raw.githubusercontent.com/mernst/travis-after-all/master/lib/travis-after-all.js | tac | tac | nodejs\nexitCode=$?\necho \"exitCode=$exitCode TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST\"\n"
  ],
  "jdk": "oraclejdk8",
  "git": {
    "depth": 9
  },
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}